//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub name: String,
    pub path: String,
    pub creator: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::file_tags::Entity")]
    FileTags,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Creator",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::file_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FileTags.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::file_tags::Relation::Tags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::file_tags::Relation::Files.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
