//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::file_tags::Entity as FileTags;
pub use super::files::Entity as Files;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;
